//! Tauri host process for the Screentime UI.
//!
//! Every command exposed here is a thin adapter over an IPC call to the
//! `screentime-agent`. Do not put business logic in this crate: the agent is
//! the source of truth, and duplicating rules in the UI process is how they
//! stop agreeing.
//!
//! Payload policy: `st-ipc` DTOs are serialized *verbatim* — no host-side
//! re-mapping into different field names. That keeps the TypeScript bindings
//! generated by ts-rs (ui/src/types/generated/) byte-compatible with what the
//! commands actually return; any drift between the two would be caught by the
//! compiler instead of at runtime.
//!
//! Error policy: failures cross the boundary as a structured
//! `{ code, message }` object rather than a formatted string, so the UI can
//! map machine codes (bad_pin, cooldown_active, …) to friendly copy without
//! parsing English.

mod ipc_client;
mod tray;

#[cfg(windows)]
mod corners {
    use std::mem::size_of;
    use windows::Win32::Foundation::HWND;
    use windows::Win32::Graphics::Dwm::{
        DwmSetWindowAttribute, DWMWA_WINDOW_CORNER_PREFERENCE, DWMWCP_DONOTROUND,
    };

    pub(crate) const SQUARE: i32 = DWMWCP_DONOTROUND.0;

    pub(crate) fn set_square_corners(hwnd: HWND) {
        let result = unsafe {
            DwmSetWindowAttribute(
                hwnd,
                DWMWA_WINDOW_CORNER_PREFERENCE,
                &SQUARE as *const i32 as *const _,
                size_of::<i32>() as u32,
            )
        };
        if let Err(e) = result {
            tracing::debug!("DwmSetWindowAttribute(SQUARE) failed: {e}");
        }
    }
}

use serde::Serialize;
use st_ipc::{ErrorCode, Response};

/// Everything the header needs, plus one host-owned fact: whether the IPC
/// round trip succeeded at all. `StatusDto` describes the agent's own state;
/// `agent_connected` describes the *link*, which only this process knows.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "snake_case")]
pub struct AgentStatus {
    pub version: String,
    pub agent_connected: bool,
    pub tracker_backend: String,
    pub filter_backend: String,
    pub tracking_available: bool,
    pub pin_configured: bool,
    pub strict_mode: bool,
}

/// Structured failure for every fallible command.
///
/// `code` mirrors [`st_ipc::ErrorCode`]'s snake_case wire tokens where the
/// agent refused, and extends the vocabulary with transport-level codes the
/// host owns: `unreachable` (pipe connect/send/read failed) and
/// `unexpected_response` (protocol mismatch — should be impossible).
#[derive(Debug, Clone, Serialize)]
pub struct CommandError {
    pub code: String,
    pub message: String,
}

impl CommandError {
    fn unreachable(e: st_ipc::transport::TransportError) -> Self {
        Self {
            code: "unreachable".into(),
            message: format!("agent unreachable: {e}"),
        }
    }

    fn unexpected() -> Self {
        Self {
            code: "unexpected_response".into(),
            message: "unexpected agent response".into(),
        }
    }
}

fn error_from(code: ErrorCode, message: String) -> CommandError {
    CommandError {
        code: serde_plain_string(code),
        message,
    }
}

/// Render an [`ErrorCode`] as its snake_case wire token. Kept in step with the
/// enum's `rename_all`; the serialization-stability test in st-ipc pins the
/// exact tokens.
fn serde_plain_string(code: ErrorCode) -> String {
    let json = serde_json::to_value(code).expect("unit enum variant always serializes");
    json.as_str()
        .expect("unit variant serializes as string")
        .into()
}

type CmdResult<T> = Result<T, CommandError>;

/// Snapshot of what the UI should show in its header.
///
/// This is intentionally a *description* of the current situation rather than a
/// list of individually queryable fields: the header must render a coherent
/// state (either "connected, tracking" *or* "disconnected") and splitting it
/// across several commands invites the two halves to disagree.
///
/// When the agent is not running, the command still succeeds but reports
/// `agent_connected: false` so the frontend renders a graceful banner instead
/// of an error state.
#[tauri::command]
fn get_status() -> AgentStatus {
    match ipc_client::request(st_ipc::Request::Status) {
        Ok(Response::Status(dto)) => AgentStatus {
            version: dto.agent_version,
            agent_connected: true,
            tracker_backend: dto.tracker_backend,
            filter_backend: dto.filter_backend,
            tracking_available: dto.tracking_available,
            pin_configured: dto.pin_configured,
            strict_mode: dto.strict_mode,
        },
        Ok(_) | Err(_) => AgentStatus {
            version: env!("CARGO_PKG_VERSION").to_string(),
            agent_connected: false,
            tracker_backend: if cfg!(windows) { "win32" } else { "x11-stub" }.into(),
            filter_backend: if cfg!(windows) {
                "windows-hosts"
            } else {
                "linux-stub"
            }
            .into(),
            tracking_available: false,
            pin_configured: false,
            strict_mode: false,
        },
    }
}

/// Dashboard payload for one local day, fetched from the agent.
#[tauri::command]
fn get_day_summary(day: i32) -> CmdResult<st_ipc::DaySummaryDto> {
    match ipc_client::request(st_ipc::Request::DaySummary {
        day: st_core::daykey::DayKey(day),
    }) {
        Ok(Response::DaySummary(dto)) => Ok(dto),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

/// Weekly dashboard payload: the 7 local days ending at `endDay` (inclusive)
/// plus the previous week's total, fetched from the agent.
#[tauri::command]
fn get_weekly_summary(end_day: i32) -> CmdResult<st_ipc::WeeklySummaryDto> {
    match ipc_client::request(st_ipc::Request::WeeklySummary {
        end_day: st_core::daykey::DayKey(end_day),
    }) {
        Ok(Response::WeeklySummary(dto)) => Ok(dto),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

/// Everything the limit editor needs: apps, categories and current limits.
#[tauri::command]
fn get_catalog() -> CmdResult<st_ipc::CatalogDto> {
    match ipc_client::request(st_ipc::Request::Catalog) {
        Ok(Response::Catalog(dto)) => Ok(dto),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

/// The reply to a successful PIN set or recovery: the one-time recovery code
/// minted for the new vault. The agent stores only its hash, so this is the
/// only chance the UI ever has to show it.
#[derive(Debug, Clone, Serialize)]
pub struct PinVaultOut {
    pub recovery_code: String,
}

#[tauri::command]
fn set_pin(new_pin: String, current_pin: Option<String>) -> CmdResult<PinVaultOut> {
    match ipc_client::request(st_ipc::Request::SetPin {
        new_pin,
        current_pin,
    }) {
        Ok(Response::PinVault { recovery_code }) => Ok(PinVaultOut { recovery_code }),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

/// Replace a forgotten PIN with its one-time recovery code. Returns the fresh
/// code minted for the new vault.
#[tauri::command]
fn recover_pin(recovery_code: String, new_pin: String) -> CmdResult<PinVaultOut> {
    match ipc_client::request(st_ipc::Request::RecoverPin {
        recovery_code,
        new_pin,
    }) {
        Ok(Response::PinVault { recovery_code }) => Ok(PinVaultOut { recovery_code }),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

/// Dismantle the vault. `credential` may be the current PIN or the standing
/// recovery code.
#[tauri::command]
fn remove_pin(credential: String) -> CmdResult<()> {
    match ipc_client::request(st_ipc::Request::RemovePin { credential }) {
        Ok(Response::Accepted { .. }) => Ok(()),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

#[tauri::command]
fn set_limit(
    target: st_ipc::LimitTargetDto,
    default_minutes: u32,
    weekday_minutes: Vec<Option<u32>>,
    enabled: bool,
    pin: String,
) -> CmdResult<String> {
    // The wire format is a fixed Monday-first 7-slot array. The host stays
    // dumb: exactly seven elements or the request is refused before any IPC
    // traffic — no padding, no truncation.
    let weekday_minutes: [Option<u32>; 7] = match weekday_minutes.try_into() {
        Ok(array) => array,
        Err(received) => {
            return Err(CommandError {
                code: "bad_request".into(),
                message: format!(
                    "weekday_minutes must be a 7-element array, got {}",
                    received.len()
                ),
            });
        }
    };
    match ipc_client::request(st_ipc::Request::SetLimit {
        target,
        default_minutes,
        weekday_minutes,
        enabled,
        pin,
    }) {
        Ok(Response::Accepted { effective_utc }) => Ok(effective_utc),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

#[tauri::command]
fn delete_limit(target: st_ipc::LimitTargetDto, pin: String) -> CmdResult<String> {
    match ipc_client::request(st_ipc::Request::DeleteLimit { target, pin }) {
        Ok(Response::Accepted { effective_utc }) => Ok(effective_utc),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

#[tauri::command]
fn grant_override(target: st_ipc::LimitTargetDto, seconds: i64, pin: String) -> CmdResult<()> {
    match ipc_client::request(st_ipc::Request::GrantOverride {
        target,
        seconds,
        pin,
    }) {
        Ok(Response::Accepted { .. }) => Ok(()),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

// -- Web filter --------------------------------------------------------------
//
// Thin adapters over the agent's web-filter IPC surface. The agent is the sole
// owner of the blocklist/rule/site tables; these commands only shape the
// request and unwrap the structured reply.

fn accepted_cmd(request: st_ipc::Request) -> CmdResult<()> {
    match ipc_client::request(request) {
        Ok(Response::Accepted { .. }) => Ok(()),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

#[tauri::command]
fn categorize(app_id: i64, primary: i64, tags: Vec<i64>) -> CmdResult<()> {
    accepted_cmd(st_ipc::Request::Categorize {
        app_id,
        primary,
        tags,
    })
}

#[derive(serde::Serialize)]
struct ManualBlocksDto {
    domains: Vec<String>,
}

#[tauri::command]
fn list_manual_blocks() -> CmdResult<ManualBlocksDto> {
    match ipc_client::request(st_ipc::Request::ListManualBlocks) {
        Ok(st_ipc::Response::ManualBlocks { domains }) => Ok(ManualBlocksDto { domains }),
        Ok(st_ipc::Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

#[tauri::command]
fn add_manual_block(domain: String) -> CmdResult<()> {
    accepted_cmd(st_ipc::Request::AddManualBlock { domain })
}

#[tauri::command]
fn remove_manual_block(domain: String) -> CmdResult<()> {
    accepted_cmd(st_ipc::Request::RemoveManualBlock { domain })
}

#[tauri::command]
fn list_schedules() -> CmdResult<st_ipc::SchedulesDto> {
    match ipc_client::request(st_ipc::Request::ListSchedules) {
        Ok(Response::Schedules(dto)) => Ok(dto),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

#[tauri::command]
fn create_schedule(
    name: String,
    weekday_mask: u8,
    start_minute: u32,
    end_minute: u32,
) -> CmdResult<st_ipc::ScheduleDto> {
    match ipc_client::request(st_ipc::Request::CreateSchedule {
        name,
        weekday_mask,
        start_minute,
        end_minute,
    }) {
        Ok(Response::ScheduleCreated(dto)) => Ok(dto),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

#[tauri::command]
fn update_schedule(
    id: i64,
    name: String,
    weekday_mask: u8,
    start_minute: u32,
    end_minute: u32,
) -> CmdResult<()> {
    accepted_cmd(st_ipc::Request::UpdateSchedule {
        id,
        name,
        weekday_mask,
        start_minute,
        end_minute,
    })
}

#[tauri::command]
fn set_schedule_enabled(id: i64, enabled: bool) -> CmdResult<()> {
    accepted_cmd(st_ipc::Request::SetScheduleEnabled { id, enabled })
}

#[tauri::command]
fn delete_schedule(id: i64) -> CmdResult<()> {
    accepted_cmd(st_ipc::Request::DeleteSchedule { id })
}

#[tauri::command]
fn list_allowlist() -> CmdResult<st_ipc::AllowlistDto> {
    match ipc_client::request(st_ipc::Request::ListAllowlist) {
        Ok(Response::Allowlist(dto)) => Ok(dto),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

#[tauri::command]
fn set_allowlist(subject_type: String, subject_id: i64, allowed: bool) -> CmdResult<()> {
    accepted_cmd(st_ipc::Request::SetAllowlist {
        subject_type,
        subject_id,
        allowed,
    })
}

#[tauri::command]
fn get_focus_session() -> CmdResult<Option<st_ipc::FocusSessionDto>> {
    match ipc_client::request(st_ipc::Request::GetFocusSession) {
        Ok(Response::FocusSession { session }) => Ok(session),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

#[tauri::command]
fn start_focus_session(duration_minutes: u32, name: Option<String>) -> CmdResult<()> {
    accepted_cmd(st_ipc::Request::StartFocusSession {
        duration_minutes,
        name,
    })
}

#[tauri::command]
fn end_focus_session(pin: Option<String>) -> CmdResult<()> {
    accepted_cmd(st_ipc::Request::EndFocusSession { pin })
}

#[tauri::command]
fn emergency_reset_network() -> CmdResult<()> {
    tray::run_emergency_network_reset();
    Ok(())
}

#[tauri::command]
fn stop_all_services(app: tauri::AppHandle) -> CmdResult<()> {
    tray::stop_all_services(&app);
    Ok(())
}

pub fn run() {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![
            get_status,
            get_day_summary,
            get_weekly_summary,
            get_catalog,
            set_pin,
            recover_pin,
            remove_pin,
            set_limit,
            delete_limit,
            grant_override,
            categorize,
            list_manual_blocks,
            add_manual_block,
            remove_manual_block,
            list_schedules,
            create_schedule,
            update_schedule,
            set_schedule_enabled,
            delete_schedule,
            list_allowlist,
            set_allowlist,
            get_focus_session,
            start_focus_session,
            end_focus_session,
            emergency_reset_network,
            stop_all_services
        ])
        .setup(|app| {
            #[cfg(windows)]
            {
                use tauri::Manager;
                if let Some(window) = app.get_webview_window("main") {
                    let hwnd = window.hwnd().expect("main window HWND");
                    corners::set_square_corners(hwnd);
                }
            }

            // Initialize system tray icon with menu and emergency actions
            if let Err(e) = tray::setup_tray(app) {
                tracing::warn!("Failed to initialize system tray icon: {e}");
            }

            Ok(())
        })
        .on_window_event(|window, event| {
            // Minimize to tray on close button so app continues monitoring in background
            if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                let _ = window.hide();
                api.prevent_close();
            }
        })
        .run(tauri::generate_context!())
        .expect("failed to launch Tauri application");
}
