//! Tauri host process for the Screentime UI.
//!
//! Every command exposed here is a thin adapter over an IPC call to the
//! `screentime-agent`. Do not put business logic in this crate: the agent is
//! the source of truth, and duplicating rules in the UI process is how they
//! stop agreeing.
//!
//! Payload policy: `st-ipc` DTOs are serialized *verbatim* — no host-side
//! re-mapping into different field names. That keeps the TypeScript bindings
//! generated by ts-rs (ui/src/types/generated/) byte-compatible with what the
//! commands actually return; any drift between the two would be caught by the
//! compiler instead of at runtime.
//!
//! Error policy: failures cross the boundary as a structured
//! `{ code, message }` object rather than a formatted string, so the UI can
//! map machine codes (bad_pin, cooldown_active, …) to friendly copy without
//! parsing English.

mod ipc_client;
mod overlay_bridge;
mod tray;
mod tray_panel;

#[cfg(windows)]
mod corners {
    use std::mem::size_of;
    use windows::Win32::Foundation::HWND;
    use windows::Win32::Graphics::Dwm::{
        DwmSetWindowAttribute, DWMWA_WINDOW_CORNER_PREFERENCE, DWMWCP_DONOTROUND,
    };

    pub(crate) const SQUARE: i32 = DWMWCP_DONOTROUND.0;

    pub(crate) fn set_square_corners(hwnd: HWND) {
        let result = unsafe {
            DwmSetWindowAttribute(
                hwnd,
                DWMWA_WINDOW_CORNER_PREFERENCE,
                &SQUARE as *const i32 as *const _,
                size_of::<i32>() as u32,
            )
        };
        if let Err(e) = result {
            tracing::debug!("DwmSetWindowAttribute(SQUARE) failed: {e}");
        }
    }
}

use serde::Serialize;
use st_ipc::{ErrorCode, Response};
use tauri::{Emitter, Manager};

/// Structured failure for every fallible command.
///
/// `code` mirrors [`st_ipc::ErrorCode`]'s snake_case wire tokens where the
/// agent refused, and extends the vocabulary with transport-level codes the
/// host owns: `unreachable` (pipe connect/send/read failed) and
/// `unexpected_response` (protocol mismatch — should be impossible).
#[derive(Debug, Clone, Serialize)]
pub struct CommandError {
    pub code: String,
    pub message: String,
}

impl CommandError {
    fn unreachable(e: st_ipc::transport::TransportError) -> Self {
        Self {
            code: "unreachable".into(),
            message: format!("agent unreachable: {e}"),
        }
    }

    fn unexpected() -> Self {
        Self {
            code: "unexpected_response".into(),
            message: "unexpected agent response".into(),
        }
    }
}

fn error_from(code: ErrorCode, message: String) -> CommandError {
    CommandError {
        code: serde_plain_string(code),
        message,
    }
}

/// Render an [`ErrorCode`] as its snake_case wire token. Kept in step with the
/// enum's `rename_all`; the serialization-stability test in st-ipc pins the
/// exact tokens.
fn serde_plain_string(code: ErrorCode) -> String {
    let json = serde_json::to_value(code).expect("unit enum variant always serializes");
    json.as_str()
        .expect("unit variant serializes as string")
        .into()
}

type CmdResult<T> = Result<T, CommandError>;

/// Agent status, verbatim. When the agent is unreachable this fails with
/// `unreachable` like every other command, and the dashboard's poll switches
/// to its offline state.
#[tauri::command]
fn get_status() -> CmdResult<st_ipc::StatusDto> {
    match ipc_client::request(st_ipc::Request::Status) {
        Ok(Response::Status(dto)) => Ok(dto),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

/// Dashboard payload for one local day, fetched from the agent.
#[tauri::command]
fn get_day_summary(day: i32) -> CmdResult<st_ipc::DaySummaryDto> {
    match ipc_client::request(st_ipc::Request::DaySummary {
        day: st_core::daykey::DayKey(day),
    }) {
        Ok(Response::DaySummary(dto)) => Ok(dto),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

/// Weekly dashboard payload: the 7 local days ending at `endDay` (inclusive)
/// plus the previous week's total, fetched from the agent.
#[tauri::command]
fn get_weekly_summary(end_day: i32) -> CmdResult<st_ipc::WeeklySummaryDto> {
    match ipc_client::request(st_ipc::Request::WeeklySummary {
        end_day: st_core::daykey::DayKey(end_day),
    }) {
        Ok(Response::WeeklySummary(dto)) => Ok(dto),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

/// Everything the limit editor needs: apps, categories and current limits.
#[tauri::command]
fn get_catalog() -> CmdResult<st_ipc::CatalogDto> {
    match ipc_client::request(st_ipc::Request::Catalog) {
        Ok(Response::Catalog(dto)) => Ok(dto),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

/// The reply to a successful PIN set or recovery: the one-time recovery code
/// minted for the new vault. The agent stores only its hash, so this is the
/// only chance the UI ever has to show it.
#[derive(Debug, Clone, Serialize)]
pub struct PinVaultOut {
    pub recovery_code: String,
}

#[tauri::command]
fn set_pin(new_pin: String, current_pin: Option<String>) -> CmdResult<PinVaultOut> {
    match ipc_client::request(st_ipc::Request::SetPin {
        new_pin,
        current_pin,
    }) {
        Ok(Response::PinVault { recovery_code }) => Ok(PinVaultOut { recovery_code }),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

/// Replace a forgotten PIN with its one-time recovery code. Returns the fresh
/// code minted for the new vault.
#[tauri::command]
fn recover_pin(recovery_code: String, new_pin: String) -> CmdResult<PinVaultOut> {
    match ipc_client::request(st_ipc::Request::RecoverPin {
        recovery_code,
        new_pin,
    }) {
        Ok(Response::PinVault { recovery_code }) => Ok(PinVaultOut { recovery_code }),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

/// Change one setting. `pin` is only required (once a PIN is configured) when
/// the agent judges the change to loosen enforcement; the UI first tries
/// without one and prompts on `bad_pin`.
#[tauri::command]
fn set_setting(key: String, value: String, pin: Option<String>) -> CmdResult<()> {
    accepted_cmd(st_ipc::Request::SetSetting { key, value, pin })
}

/// Check a PIN without changing anything (UI-only reveals).
#[tauri::command]
fn verify_pin(pin: String) -> CmdResult<()> {
    accepted_cmd(st_ipc::Request::VerifyPin { pin })
}

/// Dismantle the vault. `credential` may be the current PIN or the standing
/// recovery code.
#[tauri::command]
fn remove_pin(credential: String) -> CmdResult<()> {
    match ipc_client::request(st_ipc::Request::RemovePin { credential }) {
        Ok(Response::Accepted { .. }) => Ok(()),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

#[tauri::command]
fn set_limit(
    target: st_ipc::LimitTargetDto,
    default_minutes: u32,
    weekday_minutes: Vec<Option<u32>>,
    enabled: bool,
    pin: String,
) -> CmdResult<String> {
    // The wire format is a fixed Monday-first 7-slot array. The host stays
    // dumb: exactly seven elements or the request is refused before any IPC
    // traffic — no padding, no truncation.
    let weekday_minutes: [Option<u32>; 7] = match weekday_minutes.try_into() {
        Ok(array) => array,
        Err(received) => {
            return Err(CommandError {
                code: "bad_request".into(),
                message: format!(
                    "weekday_minutes must be a 7-element array, got {}",
                    received.len()
                ),
            });
        }
    };
    match ipc_client::request(st_ipc::Request::SetLimit {
        target,
        default_minutes,
        weekday_minutes,
        enabled,
        pin,
    }) {
        Ok(Response::Accepted { effective_utc, .. }) => Ok(effective_utc),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

#[tauri::command]
fn cancel_pending_limit(target: st_ipc::LimitTargetDto, pin: String) -> CmdResult<String> {
    match ipc_client::request(st_ipc::Request::CancelPendingLimit { target, pin }) {
        Ok(st_ipc::Response::Accepted { effective_utc, .. }) => Ok(effective_utc),
        Ok(st_ipc::Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

#[tauri::command]
fn delete_limit(target: st_ipc::LimitTargetDto, pin: String) -> CmdResult<String> {
    match ipc_client::request(st_ipc::Request::DeleteLimit { target, pin }) {
        Ok(Response::Accepted { effective_utc, .. }) => Ok(effective_utc),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

#[tauri::command]
fn grant_override(target: st_ipc::LimitTargetDto, seconds: i64, pin: String) -> CmdResult<()> {
    match ipc_client::request(st_ipc::Request::GrantOverride {
        target,
        seconds,
        pin,
    }) {
        Ok(Response::Accepted { .. }) => Ok(()),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

// -- Web filter --------------------------------------------------------------
//
// Thin adapters over the agent's web-filter IPC surface. The agent is the sole
// owner of the blocklist/rule/site tables; these commands only shape the
// request and unwrap the structured reply.

fn accepted_cmd(request: st_ipc::Request) -> CmdResult<()> {
    match ipc_client::request(request) {
        Ok(Response::Accepted { .. }) => Ok(()),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

/// Run a tray action that loosens protection (`tray::TrayAction`), once the
/// agent has checked the PIN with `VerifyPin`: allowed when no PIN is set,
/// rate limited like every other PIN check. Fails closed when the agent
/// cannot be reached, since nothing could check the PIN.
#[tauri::command]
fn run_tray_action(app: tauri::AppHandle, action: String, pin: Option<String>) -> CmdResult<()> {
    let Some(action) = tray::TrayAction::parse(&action) else {
        return Err(CommandError {
            code: "bad_request".into(),
            message: format!("unknown tray action: {action}"),
        });
    };
    accepted_cmd(st_ipc::Request::VerifyPin {
        pin: pin.unwrap_or_default(),
    })?;
    tray::run_action(&app, action);
    Ok(())
}

#[tauri::command]
fn categorize(
    app_id: i64,
    primary: Option<i64>,
    tags: Vec<i64>,
    pin: Option<String>,
) -> CmdResult<()> {
    accepted_cmd(st_ipc::Request::Categorize {
        app_id,
        primary,
        tags,
        pin,
    })
}

#[derive(serde::Serialize)]
struct ManualBlocksDto {
    domains: Vec<String>,
}

#[tauri::command]
fn list_manual_blocks() -> CmdResult<ManualBlocksDto> {
    match ipc_client::request(st_ipc::Request::ListManualBlocks) {
        Ok(st_ipc::Response::ManualBlocks { domains }) => Ok(ManualBlocksDto { domains }),
        Ok(st_ipc::Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

#[tauri::command]
fn add_manual_block(domain: String) -> CmdResult<()> {
    accepted_cmd(st_ipc::Request::AddManualBlock { domain })
}

#[tauri::command]
fn remove_manual_block(domain: String, pin: String) -> CmdResult<()> {
    accepted_cmd(st_ipc::Request::RemoveManualBlock { domain, pin })
}

#[tauri::command]
fn list_schedules() -> CmdResult<st_ipc::SchedulesDto> {
    match ipc_client::request(st_ipc::Request::ListSchedules) {
        Ok(Response::Schedules(dto)) => Ok(dto),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

/// The block screen's answer to "What were you about to do?".
#[tauri::command]
fn record_block_reason(app_id: i64, reason: String) -> CmdResult<()> {
    accepted_cmd(st_ipc::Request::RecordBlockReason { app_id, reason })
}

/// Counts of block-screen reasons between two day keys (inclusive).
#[tauri::command]
fn block_reasons(from_day: i32, to_day: i32) -> CmdResult<st_ipc::BlockReasonsDto> {
    let request = st_ipc::Request::BlockReasons {
        from_day: st_core::daykey::DayKey(from_day),
        to_day: st_core::daykey::DayKey(to_day),
    };
    match ipc_client::request(request) {
        Ok(Response::BlockReasons(dto)) => Ok(dto),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

#[tauri::command]
fn create_schedule(
    name: String,
    weekday_mask: u8,
    start_minute: u32,
    end_minute: u32,
) -> CmdResult<st_ipc::ScheduleDto> {
    match ipc_client::request(st_ipc::Request::CreateSchedule {
        name,
        weekday_mask,
        start_minute,
        end_minute,
    }) {
        Ok(Response::ScheduleCreated(dto)) => Ok(dto),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

#[tauri::command]
fn update_schedule(
    id: i64,
    name: String,
    weekday_mask: u8,
    start_minute: u32,
    end_minute: u32,
    pin: Option<String>,
) -> CmdResult<()> {
    accepted_cmd(st_ipc::Request::UpdateSchedule {
        id,
        name,
        weekday_mask,
        start_minute,
        end_minute,
        pin,
    })
}

#[tauri::command]
fn set_schedule_enabled(id: i64, enabled: bool, pin: Option<String>) -> CmdResult<()> {
    accepted_cmd(st_ipc::Request::SetScheduleEnabled { id, enabled, pin })
}

#[tauri::command]
fn delete_schedule(id: i64, pin: Option<String>) -> CmdResult<()> {
    accepted_cmd(st_ipc::Request::DeleteSchedule { id, pin })
}

#[tauri::command]
fn list_allowlist() -> CmdResult<st_ipc::AllowlistDto> {
    match ipc_client::request(st_ipc::Request::ListAllowlist) {
        Ok(Response::Allowlist(dto)) => Ok(dto),
        Ok(Response::Error { code, message }) => Err(error_from(code, message)),
        Ok(_) => Err(CommandError::unexpected()),
        Err(e) => Err(CommandError::unreachable(e)),
    }
}

#[tauri::command]
fn set_allowlist(
    subject_type: String,
    subject_id: i64,
    allowed: bool,
    pin: Option<String>,
) -> CmdResult<()> {
    accepted_cmd(st_ipc::Request::SetAllowlist {
        subject_type,
        subject_id,
        allowed,
        pin,
    })
}

/// Selectable themes, mirroring `ThemePreference` in `ui/src/hooks/useTheme.ts`.
const THEMES: [&str; 3] = ["light", "dark", "system"];

/// Map a stored preference to a current theme. Retired names written by
/// earlier versions migrate instead of being rejected, matching `useTheme`'s
/// `normalizePref` and the bootstrap script in `index.html`.
fn normalize_theme(t: &str) -> Option<&'static str> {
    let migrated = match t {
        "midnight-cobalt" | "slate-charcoal" | "cyber-emerald" | "horizon-dark"
        | "classic-dark" => "dark",
        "clean-titanium" | "nordic-frost" | "horizon-light" | "classic-light" => "light",
        other => other,
    };
    THEMES.into_iter().find(|known| *known == migrated)
}

/// Returns the user's saved theme preference from `{app_data_dir}/theme.txt`.
/// Returns `"system"` if the file doesn't exist or can't be read.
#[tauri::command]
fn get_theme(app: tauri::AppHandle) -> String {
    let path = app.path().app_data_dir().map(|d| d.join("theme.txt")).ok();
    if let Some(p) = path {
        if let Ok(s) = std::fs::read_to_string(&p) {
            if let Some(theme) = normalize_theme(s.trim()) {
                return theme.to_string();
            }
        }
    }
    "system".into()
}

/// Persists the user's theme preference to `{app_data_dir}/theme.txt` and broadcasts
/// `theme_changed` across all windows (main and overlay).
#[tauri::command]
fn set_theme(app: tauri::AppHandle, theme: String) -> CmdResult<()> {
    let Some(theme) = normalize_theme(&theme) else {
        return Err(CommandError {
            code: "invalid_theme".into(),
            message: format!("unknown theme: {theme}"),
        });
    };
    let path = app
        .path()
        .app_data_dir()
        .map(|d| d.join("theme.txt"))
        .map_err(|e| CommandError {
            code: "io_error".into(),
            message: format!("cannot resolve app data dir: {e}"),
        })?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| CommandError {
            code: "io_error".into(),
            message: format!("cannot create app data dir: {e}"),
        })?;
    }
    std::fs::write(&path, theme.as_bytes()).map_err(|e| CommandError {
        code: "io_error".into(),
        message: format!("cannot write theme file: {e}"),
    })?;
    if let Ok(local_app_data) = std::env::var("LOCALAPPDATA") {
        let p = std::path::PathBuf::from(local_app_data)
            .join("screentime")
            .join("theme.txt");
        if let Some(parent) = p.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        let _ = std::fs::write(&p, theme.as_bytes());
    }

    // Broadcast theme update across all windows
    let _ = app.emit("theme_changed", &theme);

    Ok(())
}

#[tauri::command]
fn preview_alert_sound(volume: Option<u32>) -> CmdResult<()> {
    #[cfg(windows)]
    {
        const CHIME_WAV: &[u8] = include_bytes!("../../../crates/session/src/assets/chime.wav");
        st_win32::audio::play_wav_scaled(CHIME_WAV, volume.unwrap_or(80));
    }
    #[cfg(not(windows))]
    let _ = volume;
    Ok(())
}

pub fn run() {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    tauri::Builder::default()
        .plugin(
            tauri_plugin_window_state::Builder::default()
                .with_denylist(&["overlay", "tray"])
                .build(),
        )
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
            use tauri::Manager;
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.show();
                let _ = window.set_focus();
            }
        }))
        .invoke_handler(tauri::generate_handler![
            get_status,
            get_day_summary,
            get_weekly_summary,
            get_catalog,
            set_pin,
            recover_pin,
            remove_pin,
            verify_pin,
            set_setting,
            set_limit,
            cancel_pending_limit,
            delete_limit,
            grant_override,
            categorize,
            list_manual_blocks,
            add_manual_block,
            remove_manual_block,
            list_schedules,
            create_schedule,
            update_schedule,
            set_schedule_enabled,
            delete_schedule,
            list_allowlist,
            set_allowlist,
            preview_alert_sound,
            get_theme,
            set_theme,
            overlay_bridge::get_overlay_state,
            overlay_bridge::overlay_extend,
            overlay_bridge::overlay_quit,
            overlay_bridge::hide_overlay_window,
            run_tray_action,
            record_block_reason,
            block_reasons,
            tray_panel::open_dashboard
        ])
        .setup(|app| {
            if let Some(overlay_win) = app.get_webview_window("overlay") {
                let _ = overlay_win.hide();
            }

            let bridge_state = overlay_bridge::OverlayBridgeState::new();
            app.manage(bridge_state.clone());
            overlay_bridge::start_bridge_server(app.handle().clone(), bridge_state.0.clone());

            #[cfg(windows)]
            {
                use tauri::Manager;
                if let Some(window) = app.get_webview_window("main") {
                    if let Ok(hwnd) = window.hwnd() {
                        corners::set_square_corners(hwnd);
                    }
                }
            }

            #[cfg(windows)]
            {
                use std::os::windows::process::CommandExt;
                // Auto-launch the session tracker alongside the UI.
                // The tracker uses a single-instance mutex, so this is perfectly
                // safe to call blindly — it will just exit if already running.
                if let Ok(exe) = std::env::current_exe() {
                    if let Some(dir) = exe.parent() {
                        let tracker = dir.join("bin").join("screentime-session.exe");
                        if tracker.exists() {
                            let _ = std::process::Command::new(tracker)
                                .creation_flags(0x08000000) // CREATE_NO_WINDOW
                                .spawn();
                        }
                    }
                }
            }

            // Initialize system tray icon with menu and emergency actions
            tray_panel::setup(app);
            if let Err(e) = tray::setup_tray(app) {
                tracing::warn!("Failed to initialize system tray icon: {e}");
            }

            Ok(())
        })
        .on_window_event(|window, event| {
            // Minimize to tray on close button so app continues monitoring in background
            if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                let _ = window.hide();
                api.prevent_close();
            }
        })
        .run(tauri::generate_context!())
        .expect("failed to launch Tauri application");
}

#[cfg(test)]
mod tests {
    use super::normalize_theme;

    #[test]
    fn current_themes_pass_through_and_retired_ones_migrate() {
        assert_eq!(normalize_theme("light"), Some("light"));
        assert_eq!(normalize_theme("dark"), Some("dark"));
        assert_eq!(normalize_theme("system"), Some("system"));
        // Retired names keep their light/dark side.
        assert_eq!(normalize_theme("midnight-cobalt"), Some("dark"));
        assert_eq!(normalize_theme("slate-charcoal"), Some("dark"));
        assert_eq!(normalize_theme("nordic-frost"), Some("light"));
        assert_eq!(normalize_theme("classic-light"), Some("light"));
        assert_eq!(normalize_theme("neon-pink"), None);
    }
}
