; Tether's own installer wording, in every language the installer ships
; (tauri.conf.json > bundle > windows > nsis > languages). Tauri's generic
; strings (desktop shortcut, reinstall page) come from its language files.
; Voice: docs/DESIGN_SYSTEM.md section 8 (plain words, sentence case).
;
; Included by installer.nsi after the MUI_LANGUAGE lines.

; ---------------------------------------------------------------- English
LangString tetherWelcomeTitle ${LANG_ENGLISH} "Welcome to Tether"
LangString tetherWelcomeText ${LANG_ENGLISH} "Tether shows where your screen time goes and steps in when a budget runs out.$\r$\n$\r$\nThis installs the Tether app and a small background service. The service keeps limits working after a restart, for every account on this PC.$\r$\n$\r$\nWhen it finishes, Tether asks who it's for and helps you set starting budgets and a PIN."
LangString tetherDirTitle ${LANG_ENGLISH} "Choose a folder"
LangString tetherDirSubtitle ${LANG_ENGLISH} "The suggested folder is right for most people."
LangString tetherDirText ${LANG_ENGLISH} "Tether will be installed in this folder. To use a different one, choose Browse."
LangString tetherInstallingTitle ${LANG_ENGLISH} "Installing Tether"
LangString tetherInstallingSubtitle ${LANG_ENGLISH} "This takes about a minute."
LangString tetherInstalledTitle ${LANG_ENGLISH} "Tether is installed"
LangString tetherInstalledSubtitle ${LANG_ENGLISH} "The background service is running."
LangString tetherAbortedTitle ${LANG_ENGLISH} "Installation stopped"
LangString tetherAbortedSubtitle ${LANG_ENGLISH} "Tether was not installed."
LangString tetherFinishTitle ${LANG_ENGLISH} "Tether is ready"
LangString tetherFinishText ${LANG_ENGLISH} "Tether starts with Windows and keeps working in the background.$\r$\n$\r$\nOpen Tether to choose who it's for, pick starting budgets and set a PIN."
LangString tetherOpenNow ${LANG_ENGLISH} "Open Tether now"
LangString tetherAbortWarning ${LANG_ENGLISH} "Stop installing Tether?"
LangString tetherDetailClosing ${LANG_ENGLISH} "Closing Tether if it is running..."
LangString tetherDetailService ${LANG_ENGLISH} "Starting the Tether service..."
LangString tetherDetailServiceFailed ${LANG_ENGLISH} "The Tether service did not start (error $0). Restart the PC; if it still does not start, reinstall Tether."
LangString tetherServiceFailedSubtitle ${LANG_ENGLISH} "The background service did not start. Restart the PC to finish."
LangString tetherDetailStartup ${LANG_ENGLISH} "Adding Tether to Windows startup..."
LangString tetherDetailOverlay ${LANG_ENGLISH} "Keeping overlay tools away from Tether's windows..."
LangString tetherDetailTracking ${LANG_ENGLISH} "Starting tracking for this account..."
LangString tetherUnTitle ${LANG_ENGLISH} "Remove Tether"
LangString tetherUnSubtitle ${LANG_ENGLISH} "Limits stop applying once Tether is removed."
LangString tetherUnText ${LANG_ENGLISH} "Tether, its background service and its startup entry will be removed from this folder:"
LangString tetherUnDeleteData ${LANG_ENGLISH} "Also delete usage history and settings"
LangString tetherUnRestoreDns ${LANG_ENGLISH} "Turn off Family DNS and restore the previous network DNS"
LangString tetherUnAbortWarning ${LANG_ENGLISH} "Stop removing Tether?"
LangString tetherUnDetailService ${LANG_ENGLISH} "Stopping the Tether service..."
LangString tetherUnDetailDns ${LANG_ENGLISH} "Restoring the previous network DNS..."
LangString tetherUnDetailRemoveService ${LANG_ENGLISH} "Removing the Tether service..."

; ----------------------------------------------------------------- Arabic
!ifdef LANG_ARABIC
LangString tetherWelcomeTitle ${LANG_ARABIC} "مرحبًا بك في Tether"
LangString tetherWelcomeText ${LANG_ARABIC} "يُظهر Tether أين يذهب وقتك أمام الشاشة، ويتدخّل عندما تنفد الميزانية.$\r$\n$\r$\nيثبّت هذا المعالج تطبيق Tether وخدمة صغيرة تعمل في الخلفية. تُبقي الخدمة الحدود فعّالة بعد إعادة التشغيل، ولكل الحسابات على هذا الجهاز.$\r$\n$\r$\nعند الانتهاء يسألك Tether لمن يُستخدم، ويساعدك على وضع الميزانيات الأولى ورمز PIN."
LangString tetherDirTitle ${LANG_ARABIC} "اختر مجلدًا"
LangString tetherDirSubtitle ${LANG_ARABIC} "المجلد المقترح مناسب لمعظم الناس."
LangString tetherDirText ${LANG_ARABIC} "سيُثبَّت Tether في هذا المجلد. لاختيار مجلد آخر، اختر استعراض."
LangString tetherInstallingTitle ${LANG_ARABIC} "جارٍ تثبيت Tether"
LangString tetherInstallingSubtitle ${LANG_ARABIC} "يستغرق هذا دقيقة تقريبًا."
LangString tetherInstalledTitle ${LANG_ARABIC} "تم تثبيت Tether"
LangString tetherInstalledSubtitle ${LANG_ARABIC} "الخدمة تعمل في الخلفية."
LangString tetherAbortedTitle ${LANG_ARABIC} "توقف التثبيت"
LangString tetherAbortedSubtitle ${LANG_ARABIC} "لم يُثبَّت Tether."
LangString tetherFinishTitle ${LANG_ARABIC} "Tether جاهز"
LangString tetherFinishText ${LANG_ARABIC} "يبدأ Tether مع تشغيل Windows ويعمل في الخلفية.$\r$\n$\r$\nافتح Tether لتختار لمن يُستخدم، وتحدد الميزانيات الأولى ورمز PIN."
LangString tetherOpenNow ${LANG_ARABIC} "افتح Tether الآن"
LangString tetherAbortWarning ${LANG_ARABIC} "هل تريد إيقاف تثبيت Tether؟"
LangString tetherDetailClosing ${LANG_ARABIC} "إغلاق Tether إن كان يعمل..."
LangString tetherDetailService ${LANG_ARABIC} "تشغيل خدمة Tether..."
LangString tetherDetailServiceFailed ${LANG_ARABIC} "لم تبدأ خدمة Tether (الخطأ $0). أعد تشغيل الجهاز، وإن لم تبدأ بعدها فأعد تثبيت Tether."
LangString tetherServiceFailedSubtitle ${LANG_ARABIC} "لم تبدأ الخدمة في الخلفية. أعد تشغيل الجهاز لإكمال التثبيت."
LangString tetherDetailStartup ${LANG_ARABIC} "إضافة Tether إلى بدء تشغيل Windows..."
LangString tetherDetailOverlay ${LANG_ARABIC} "إبعاد أدوات التراكب عن نوافذ Tether..."
LangString tetherDetailTracking ${LANG_ARABIC} "بدء التتبّع لهذا الحساب..."
LangString tetherUnTitle ${LANG_ARABIC} "إزالة Tether"
LangString tetherUnSubtitle ${LANG_ARABIC} "تتوقف الحدود عن العمل بعد إزالة Tether."
LangString tetherUnText ${LANG_ARABIC} "ستُزال Tether وخدمتها في الخلفية وإدخال بدء التشغيل من هذا المجلد:"
LangString tetherUnDeleteData ${LANG_ARABIC} "احذف أيضًا سجل الاستخدام والإعدادات"
LangString tetherUnRestoreDns ${LANG_ARABIC} "أوقف حماية DNS العائلية واستعد إعدادات DNS السابقة للشبكة"
LangString tetherUnAbortWarning ${LANG_ARABIC} "هل تريد إيقاف إزالة Tether؟"
LangString tetherUnDetailService ${LANG_ARABIC} "إيقاف خدمة Tether..."
LangString tetherUnDetailDns ${LANG_ARABIC} "استعادة إعدادات DNS السابقة للشبكة..."
LangString tetherUnDetailRemoveService ${LANG_ARABIC} "إزالة خدمة Tether..."
!endif
