[package]
name = "st-enforce-win"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
st-core.workspace = true
tracing.workspace = true

[target.'cfg(windows)'.dependencies]
st-win32 = { path = "../st-win32" }
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
] }
